"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-10 21:19:11.886730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constraint_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=12), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('target_id', sa.String(length=80), nullable=True),
    sa.Column('days', sa.JSON(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('rule_field', sa.String(length=40), nullable=True),
    sa.Column('rule_value', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=80), nullable=True),
    sa.Column('lock_timeslot', sa.Integer(), nullable=True),
    sa.Column('lock_room', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rooms',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('building', sa.String(length=80), nullable=False),
    sa.Column('room_type', sa.String(length=16), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.String(length=40), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('base_version_id', sa.Integer(), nullable=True),
    sa.Column('constraint_id', sa.Integer(), nullable=True),
    sa.Column('affected_json', sa.Text(), nullable=True),
    sa.Column('options_json', sa.Text(), nullable=True),
    sa.Column('selected_rank', sa.Integer(), nullable=True),
    sa.Column('auto_selected', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by', sa.String(length=80), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('result_version_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('timetables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('term', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faculty',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('max_daily_load', sa.Integer(), nullable=False),
    sa.Column('max_weekly_load', sa.Integer(), nullable=False),
    sa.Column('max_consecutive', sa.Integer(), nullable=False),
    sa.Column('subjects', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'name')
    )
    op.create_table('room_blocks',
    sa.Column('room_id', sa.String(length=40), nullable=False),
    sa.Column('timeslot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'timeslot_id')
    )
    op.create_table('room_capabilities',
    sa.Column('room_id', sa.String(length=40), nullable=False),
    sa.Column('capability', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'capability')
    )
    op.create_table('timetable_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('solver_status', sa.String(length=16), nullable=False),
    sa.Column('objective', sa.Float(), nullable=True),
    sa.Column('best_bound', sa.Float(), nullable=True),
    sa.Column('solve_seconds', sa.Float(), nullable=False),
    sa.Column('source_version_id', sa.Integer(), nullable=True),
    sa.Column('changed_count', sa.Integer(), nullable=True),
    sa.Column('unchanged_count', sa.Integer(), nullable=True),
    sa.Column('retention_pct', sa.Float(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('instance_json', sa.Text(), nullable=False),
    sa.Column('pending_rules_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_version_id'], ['timetable_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timetable_id', 'number')
    )
    op.create_table('academic_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'number')
    )
    op.create_table('faculty_slots',
    sa.Column('faculty_id', sa.String(length=40), nullable=False),
    sa.Column('timeslot_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('faculty_id', 'timeslot_id', 'kind')
    )
    op.create_table('scheduled_sessions',
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=80), nullable=False),
    sa.Column('timeslot_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['timetable_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id', 'session_id')
    )
    op.create_table('semesters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year_id', 'number')
    )
    op.create_table('batches',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batch_blocks',
    sa.Column('batch_id', sa.String(length=40), nullable=False),
    sa.Column('timeslot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('batch_id', 'timeslot_id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('faculty_id', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('sessions_per_week', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.String(length=16), nullable=False),
    sa.Column('required_capability', sa.String(length=60), nullable=True),
    sa.Column('elective_key', sa.String(length=60), nullable=True),
    sa.Column('headcount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'code', 'category')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('faculty_id', sa.String(length=40), nullable=True),
    sa.Column('batch_id', sa.String(length=40), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('auth_sessions',
    sa.Column('token_digest', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_digest')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.String(length=40), nullable=False),
    sa.Column('faculty_id', sa.String(length=40), nullable=False),
    sa.Column('subject_code', sa.String(length=20), nullable=False),
    sa.Column('subject_name', sa.String(length=160), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.String(length=16), nullable=False),
    sa.Column('elective_group', sa.String(length=80), nullable=True),
    sa.Column('headcount', sa.Integer(), nullable=True),
    sa.Column('required_capability', sa.String(length=60), nullable=True),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('auth_sessions')
    op.drop_table('users')
    op.drop_table('subjects')
    op.drop_table('batch_blocks')
    op.drop_table('batches')
    op.drop_table('semesters')
    op.drop_table('scheduled_sessions')
    op.drop_table('faculty_slots')
    op.drop_table('academic_years')
    op.drop_table('timetable_versions')
    op.drop_table('room_capabilities')
    op.drop_table('room_blocks')
    op.drop_table('programs')
    op.drop_table('faculty')
    op.drop_table('timetables')
    op.drop_table('settings')
    op.drop_table('schedule_requests')
    op.drop_table('rooms')
    op.drop_table('departments')
    op.drop_table('constraint_records')
    # ### end Alembic commands ###
